### ISSUE TITLE
Datadog support

### ISSUE THREAD

**Issue by cpoissonnier** [redaxmedia/chroma-feedback#111]
Hello Henry !

That would be great to support Datadog as well. Being able to have a device that turns red when there is too many error in production would be absolutely great.

I might be able to help, but what do you think about this kind of new integration ?

## How to implement
Datadog has a python library : https://github.com/DataDog/datadog-api-client-python

We could use the API : https://docs.datadoghq.com/api/latest/monitors/#get-a-monitors-details
The endpoint `https://api.datadoghq.eu/api/v1/monitor/:id` has an `overall_state` field that can be `Alert`,`Ignored`,`No Data`,`OK`,`Skipped`,`Unknown`,`Warn`

For the configuration, we will need : 
- base url (datadog has multiple domains (api.datadoghq.com, api.datadoghq.eu, ...))
- api-key
- application-key
- monitoring id

**Comment by redaxmedia** [comment]
@cpoissonnier Sure, I would be happy to add support - but I need an account there and some background information. Are you open for a pairing session?

**Comment by redaxmedia** [comment]
Closed via https://github.com/redaxmedia/chroma-feedback/pull/112
