### ISSUE TITLE
Support for Corsair

### ISSUE THREAD

**Issue by redaxmedia** [redaxmedia/chroma-feedback#29]
This is the [ckb daemon manuel](https://github.com/ckb-next/ckb-next/wiki/CKB-Daemon-Manual) that describes the following commands:

Get all devices:

```
cat /dev/input/ckb0/connected
```

Change color:

```
echo rgb ff0000 > /dev/input/ckb1/cmd
```

There is an emulator called [FaKeyboard](https://github.com/ckb-next/FaKeyboard) for ckb:

Installation:

```
git clone git@github.com:ckb-next/FaKeyboard.git
cd src
make
```
Usage:

```
./hid-keyboard 
sudo usbip attach -r 127.0.0.1 -b 1-1
```

**Comment by redaxmedia** [comment]
I actually found the https://github.com/mattanger/ckb-next/wiki/CKB-Daemon-Manual site that looks quite promising to me because it is easy to run shell scripts via Python:

```
import subprocess
subprocess.run(["ls", "-l"])
```

I tried the following but ckb-next DOES NOT update the colors in the GUI with the ff0000 color :-(

```
echo rgb ff0000 > /dev/input/ckb1/cmd
```

The devices is connected according to:

```
/dev/input$ cat /dev/input/ckb0/connected
> dev/input/ckb1 01234567890123456789012345678901 Generic Fake Gaming Keyboard
```

So the plan would be...

1. Parse /dev/input/ckb0/connected for all devices
1. Using `echo rgb ff0000 > /dev/input/ckb*/cmd` for static color
1. Using some kind of interval with echo `rgb ff0000 > /dev/input/ckb*/cmd` for pulsating color

**Comment by redaxmedia** [comment]
Closed as there is no public API at the moment.

**Comment by redaxmedia** [comment]
Too hard without testing devices and a public Python powered API.

**Comment by redaxmedia** [comment]
@jqassar Are you interested to add support for that? In case you don't have a Corsair device ... pick one and I gonna pay it:

https://github.com/ckb-next/ckb-next/wiki/Supported-Hardware

**Comment by jqassar** [comment]
If I were to look at a 'next' issue, I would work on adding support for Terraform Cloud/Enterprise as a producer before worrying about new consumers.  After that, though, maybe.  I don't need a keyboard to test that if the fake keyboard works, but I'm having a little trouble setting it up.

**Comment by redaxmedia** [comment]
I prefer to test again a real devices... so let me know if you need to replace mouse or keyboard
