### ISSUE TITLE
None CI inputs

### ISSUE THREAD

**Issue by titilambert** [redaxmedia/chroma-feedback#45]
Hello,

I'm wondering if you would accept PR about none CI inputs ?
Here some example:
* Desktop notifications (using dbus, like flashing if I got a new notification on my desktop)
* Terminal plugins (ie Terminator plugin which could change the color of something if the current focused terminal is running a root user)
* Color thresholds based on the number of emails
* Any other idea ???

**Comment by redaxmedia** [comment]
Regards to Montreal,

at this moment there is no plan to change the basic idea behind Chroma Feedback as there are countless possibilities for different kind of providers and consumers.

Still, I see potential to open this software for other use cases:

1. Allow third party [providers](https://github.com/redaxmedia/chroma-feedback/blob/master/chroma_feedback/provider/core.py) and [consumers](https://github.com/redaxmedia/chroma-feedback/blob/master/chroma_feedback/consumer/core.py) autoloading via additional arguments like:

```
chroma-feedback --provider-plugin=chroma-feedback-plugin --consumer-plugin=chroma-feedback-plugin
```

2. Extract two core libaries from Chroma Feedback that are no longer related to RGB only on the consumer side and CI only on the provider side.

**Comment by redaxmedia** [comment]
No response, therfore closed

**Comment by redaxmedia** [comment]
@titilambert I would like to inform you that I recently added [custom producer](https://github.com/redaxmedia/chroma-feedback#custom) that can work like a middleware.

1. Create a local / remote API that is connected to a third party service or device
1. Utilize the [custom producer](https://github.com/redaxmedia/chroma-feedback#custom) against your local / remote API
1. Enjoy!
