### ISSUE TITLE
Fix Bamboo project and plan API calls

### ISSUE THREAD

**Issue by jqassar** [redaxmedia/chroma-feedback#48]
The Bamboo producer has discrepancies in how it parses results coming from a project (a collection of plans) versus a single plan.

Assume a Bamboo project (key ACME) with three plans within it (keys ANVIL, BOMB, DYNAMITE).  A user can ask the API for results from the ACME project, or pull an individual build result calling for ACME-ANVIL.

Expected behavior for this use case:

- Using the project slug (--bamboo-slug ACME) returns three build status messages, one for each plan in ACME.
- Using the plan slug (--bamboo-slug ACME-ANVIL) returns one build status message for the latest build of the ANVIL plan.

Observed behavior:
- Using the project slug (--bamboo-slug ACME) returns only the first build plan result within it, even if it contains multiple plans.
- Using the plan slug acts as it should.  However, the API call needs to be changed (see below).

Cause:

The data normalization is returning only the first result of the call to the results API, rather than iterating over the entire result.  This in and of itself is easy to fix, but it leads to a second issue: Once the entire result set is shown, the project shows all build status messages, but the _plan_ shows 25 (the default) builds, which is also unhelpful.  This is because the API being used currently works for both projects and plans.

Solution:

In all cases, the data normalization needs to be changed to iterate over the entire result object.  But what should that object be?

The results API has many formats.  ../result/ACME and ../result/ACME-ANVIL both return a similar data structure (returning 25 results.result objects), but take different qualifiers and parameters.  In order to get all results for a project but only the _latest_ result for a plan, a _third_ call, ../result/ACME-ANVIL-latest, must be used.  Its data structure is that of a single result object, which means the producer's behavior has to change slightly as well.

**Comment by redaxmedia** [comment]
Hey,

thank you for that contribution.

Unfortunately it takes until March since I'm back at home to fiddle around with Bamboo / Docker, but I can just point out some basics points.

1. Only the latest build should be shown to reflect the current state of the software
1. Let's support the slug formats `projectKey` and `plan/projectKey`
1. What about the idea to use `-latest` prefix everytime and not conditionally

Currently integrated:
http://myhost.com:8085/bamboo/rest/api/latest/result/{projectKey} [GET]

To be integrated:
http://myhost.com:8085/bamboo/rest/api/latest/result/{projectKey}-latest [GET]
http://myhost.com:8085/bamboo/rest/api/latest/result/{plan/projectKey}-latest [GET]

**Comment by jqassar** [comment]
Thanks for taking a look at it.  Let me see if I can answer your points, but just be aware that what you read was mostly correct.  The PR is just a matter of returning the appropriate amount of results for each situation.

1. Latest build is definitely the right way to go.
2. Note that the API is not hierarchical in that sense.  For a long time, projects were not even a first-class object in Bamboo.  People who use Bamboo frequently are going to be familiar with the PROJECT-PLAN key format and *not* PROJECT/PLAN, which doesn't exist at all.
3. The project API call (result/{projectKey}) does latest status by default and doesn't provide a 'latest' keyword. If you think about it, that makes sense (there is no way to pass in a build number).

**Comment by jqassar** [comment]
To explain just a bit more:

- Bamboo uses the format PROJECT-PLAN-JOB (dashes are delimiters and are reserved).
- There is no such thing as getting information from the API about PLAN, by that name. You can only get information about the identifier 'PROJECT-PLAN', or 'PROJECT' alone.

So, the API calls the PR supports are:
http://myhost.com:8085/bamboo/rest/api/latest/result/PROJECT
http://myhost.com:8085/bamboo/rest/api/latest/result/PROJECT-PLAN-latest

http://myhost.com:8085/bamboo/rest/api/latest/result/PROJECT-latest is not a valid call.

The PR will return the latest build for every plan in a project, the latest build for a single plan, and (by specifying multiple plans) you can get the latest builds of plans across various projects.

**Comment by redaxmedia** [comment]
Thanks for pointing out the details like their `-` delimiter standard. I never worked with Bamboo and just did a basic implementation...

According to the `-latest` suggestion. I read their API docs and for me it looked valid:
https://docs.atlassian.com/atlassian-bamboo/REST/5.5.0/#d2e174

Anyway - there is a code review on your PR since a couple of days. Once you solved the issues, we are fine to merge it. Let me know what you think...

Just for being curious: what consumer are you using by the way? :-)

**Comment by jqassar** [comment]
I see how that might look possible, but I should point out that the dashes in the call you're linking are required, not optional.  The only calls in the results APT which take 'latest' as a replacement for a build number are the calls for single plan status, which are these two:

http://myhost.com:8085/bamboo/rest/api/latest/result/{projectKey}-{buildKey}-{buildNumber : ([0-9]+)|(latest)} [GET]
http://myhost.com:8085/bamboo/rest/api/latest/result/{projectKey}-{buildKey}/{buildNumber : ([0-9]+)|(latest)} [GET]

(Notice they're actually the exact same call except for the / replacing the -.)

Anyway, I can expand the function however you like.  My intention was to fix it minimally, because projects are literally unable to have dashes in them.  You mention the code review comments, but I'm a little confused.  Where should I be looking for them?  I only see a comment about not worrying about the coveralls output.

**Comment by jqassar** [comment]
Also, regarding your question about consumers: I'm using a blink1 for testing, and will be expanding that to use Openrazer for build statuses.  If that works out well, I'm intending to look at adding a producer for Terraform Enterprise/Cloud statuses.

**Comment by redaxmedia** [comment]
Sorry, I forgot to submit the code review - you should now see my comments. I'm fine with with permanent `-latest` or a `processSlug` method, this is upon your personal opinion.

It would be great to have another producer - is Terraform Enterprise something like a pipeline management?

Last but not least, this is my build light setup:
https://twitter.com/redaxmedia/status/1149469978682281985/photo/1

**Comment by redaxmedia** [comment]
@jqassar Support for Bamboo plans landed in the master - I adjusted everything to the requested changes. Keep in mind that pytest now works with multiple `BAMBOO_` environment variables.

- `BAMBOO_HOST`
- `BAMBOO_PROJECT_SLUG`
- `BAMBOO_PLAN_SLUG`
- `BAMBOO_USERNAME`
- `BAMBOO_TOKEN`

Please test it and give me the okay for a release

1. Clone repository
1. Copy `bin/chroma-feedback` to ` chroma-feedback`
1. Use ./chroma-feedback --producer=bamboo ...` to test against development version

Please confirm one last thing - is that else correct as it differs from the original code:

```python
if 'results' in data and 'result' in data['results']:
	for plan in data['results']['result']:
		result.append(normalize_data(plan))
else:
	result.append(normalize_data(data))
```

I rather would expect something like thatt:

```python
if 'results' in data and 'result' in data['results']:
	if 'plan' in data['results']['result']:
		for plan in data['results']['result']:
			result.append(normalize_data(plan))
	else:
		result.append(normalize_data(data))
```

**Comment by jqassar** [comment]
Thank you for taking a look at this!  I'm sorry for not getting to the fixes, I was offline for a little while.

To answer your question (I think), you're using elif and I'm using else.  Either is fine, but I don't think the difference matters much because you have to get a valid response to even enter that block.  The error handling which already exists here catches the cases with empty projects or incorrect keys with the 'right' result ('Result not found!', in both cases.)

For your "expected" code, 'plan' as a key doesn't actually exist at the result level.  Result is an array of unnamed dicts, each of which has a 'plan' key in it (that isn't read; 'key' and 'buildState' are used).  Because it's ordered, if you assume that Bamboo returns them in descending order you _could_ assume the first result is the right one.  Then the difference would be using the same call to iterate the results (project) versus calling get first (plan).  I'm not used to assuming the ordering, but I could test that method if you want.  get_slug then is used to choose the result rather than the API call.

This is all a roundabout way of saying that your code in master seems to work right now.  :)  There is an issue with *my* mouse for failed output, but that needs more thought on my part and is outside the scope of this PR.  Release away, I say!

**Comment by redaxmedia** [comment]
I had to rush everything a bit because of my upcoming vavaction. Just release version 7.1.0 to PyPi... that being sad, I am looking forward to more contributions.

Consider to give Chroma Feedback a star on GitHub :-)

Thank you
