### ISSUE TITLE
Do we need logo_{effect} and scroll_{effect} or is this included by {effect} call

### ISSUE THREAD

**Issue by redaxmedia** [redaxmedia/chroma-feedback#53]
@jqassar First of all, the `OR` you added have been rewritten to more readable conditions:

Commit: https://github.com/redaxmedia/chroma-feedback/commit/defffdd5e3b7c05bfd89a1bebfc7309449c31b39

```python
def static_device(device : Any, state : Dict[str, Any]) -> bool:
	if device.has('brightness'):
		device.brightness = state['brightness'][0]
	if device.fx.has('logo_static'):
		return device.fx.misc.logo.static(state['rgb'][0], state['rgb'][1], state['rgb'][2])
	if device.fx.has('scroll_static'):
		return device.fx.misc.scroll_wheel.static(state['rgb'][0], state['rgb'][1], state['rgb'][2])
	if device.fx.has('static'):
		return device.fx.static(state['rgb'][0], state['rgb'][1], state['rgb'][2])
	return False
```

This brought me to the point that we properly just need the basic `{effect}` call as they properly contain the `logo_{effect}` and `scroll_{effect}`:

```python
def static_device(device : Any, state : Dict[str, Any]) -> bool:
	if device.has('brightness'):
		device.brightness = state['brightness'][0]
	if device.fx.has('static'):
		return device.fx.static(state['rgb'][0], state['rgb'][1], state['rgb'][2])
	return False
```

I push this to the master - please test the code with your devices.

Commit: https://github.com/redaxmedia/chroma-feedback/commit/617421dc1919b4c7f7aba0c11f84186b3c1b117a

**Comment by redaxmedia** [comment]
@terrycain Please answer my question related to the OpenRazer API ... thanks

**Comment by jqassar** [comment]
So, 7.2.0 is completely broken for me.

- First, that first commit (defffdd) would have ONLY lit the logo, even if there was a Chroma-enabled scroll wheel on the device.  The bitwise OR was there in the block to ensure that *both* lights have their calls set up.  The alternative, which I did write but dropped because I thought it was _not_ cleaner, was:
```
def static_device(device : Any, state : Dict[str, Any]) -> bool:
	if device.has('brightness'):
		device.brightness = state['brightness'][0]
	if device.fx.has('logo_static') or device.fx.has('scroll_static'):
		logo = device.fx.misc.logo.static(state['rgb'][0], state['rgb'][1], state['rgb'][2])
		scroll = device.fx.misc.scroll_wheel.static(state['rgb'][0], state['rgb'][1], state['rgb'][2])
		return logo or scroll
	if device.fx.has('static'):
		return device.fx.static(state['rgb'][0], state['rgb'][1], state['rgb'][2])
	return False
```
- In the second commit (617421d), you're suggesting that device.fx.static will work, and that just doesn't seem to work for devices that support MiscLighting.  If you run device.fx._capabilities and look at the output (you can see a sample in my comments on https://github.com/redaxmedia/chroma-feedback/issues/51), you will see that if static is False at the top level, you won't be able to call device.fx.static directly.  If I'm wrong about that, please let me know what devices support this.

Direct API tests on my Mamba Wireless (2018) using openrazer (crian's mamba device fork):
```
# List all capabilities for the first device <- This is really important!
python3 -c "from openrazer.client import DeviceManager; a = DeviceManager(); print(a.devices[0].fx._capabilities)"
# Expected?: red LED across entire mouse 
# Actual: 'False', no lighting update
python3 -c "from openrazer.client import DeviceManager; a = DeviceManager(); print(a.devices[0].fx.static(255,0,0))"
```
```
# OpenRazer 7.2.0 call to successful build with latest update:
chroma-feedback 7.2.0 by Henry Ruhs
/ Build of ACME-ANVIL-5 on bamboo passed
# Expected: Build result output with static lighting change
# Actual: Build result output with no lighting change

# OpenRazer 7.2.0 call to failed build with latest update:
chroma-feedback 7.2.0 by Henry Ruhs
x Build of ACME-HAMMER-1 on bamboo failed
# Expected: Build result output with pulsing lighting change
# Actual: Build result output with no lighting change
```

PS: Just so that we set our expectations here, I'm not used to having reviewed and accepted PRs completely rewritten immediately after they are merged.  I already tried (in various combinations) what you have placed into the code and knew that it would not work for my devices.

I would prefer that we test out and try these alternate mechanisms during the review process, as well as address any concerns you have about syntax or implementation.  In order for me to see where you are coming from with your testing, it would be helpful if you could tell me what devices you're using to test with and what the capabilities output looks like for you:
```
python3 -c "from openrazer.client import DeviceManager; a = DeviceManager(); print(a.devices[0].fx._capabilities)"
```

**Comment by jqassar** [comment]
My question for the OpenRazer API people would be whether or not there are shortcuts that set an effect across all lights on a device, such as all_static or all_breath_single.  If there is meant to be such a method, I haven't yet seen it, nor do I currently see a method that sets an effect across all lighting APIs.

**Comment by redaxmedia** [comment]
Okay,

I have to apologize to change the code inside the master and not inside a feature branch.

Turns out that I my "Mamba Tournament Edition" mouse does not have the MiscLightning compared to the old mouse I had before. Therefore I had a wrong conclusion...

Using the `or` in the condition and the bitwise `|` inside the call looked strange to me... for the moment I reverted it to `and` - does this work for you?

We really need something that works for the complete MiscLightning because there is:

+ logo
+ scroll
+ left
+ right
+ backlight

**Comment by jqassar** [comment]
I agree that adding something (and command-line options) to activate all (supported) lights, specified lights, and effects would be generally useful across the whole tool.

**Comment by redaxmedia** [comment]
@jqassar Just pushed my (untested as lack of hardware) approach to the develop branch:
https://github.com/redaxmedia/chroma-feedback/blob/develop/chroma_feedback/consumer/razer_chroma/device.py

Not sure if `effect_state`will become / stay `True` if only a single part is possitive...

Please give it a try... and improve it as needed

**Comment by jqassar** [comment]
Generally speaking, I like the concept.  Two issues at the moment:
1) master changes the lighting but develop doesn't:
```
~/work/chroma-feedback ((HEAD detached at upstream/master)) $  ./chroma-feedback --... --consumer=razer_chroma --razer-chroma-device "Razer Mamba Wireless (Wired)"
chroma-feedback 7.2.0 by Henry Ruhs

✔ Build of ACME-ANVIL-2636 on bamboo passed

✔ Setting Razer Mamba Wireless (Wired) to build passed.
(lighting effect message is output and lights change)

~/work/chroma-feedback ((HEAD detached at upstream/develop)) $  ./chroma-feedback ... --consumer=razer_chroma --razer-chroma-device "Razer Mamba Wireless (Wired)"
chroma-feedback 7.2.0 by Henry Ruhs

✔ Build of ACME-ANVIL-2636 on bamboo passed

(note no effect-setting message)
```
2) pulsate_device method still has a reference to breath_single.

I can look into tracking it down some time in the near future.

**Comment by redaxmedia** [comment]
Thanks for testing... I wait for the release until you contributed a fix. Take your time...

**Comment by redaxmedia** [comment]
Just fixed the syntax and logic in `misc_effect` method. Is this working for now?

**Comment by jqassar** [comment]
There were some other issues.  I have fixes in place and can put them up for review.

**Comment by jqassar** [comment]
Looks like you've already done 99% of what I was thinking, so....

There are a couple of tweaks that need to be made to make it work correctly for scroll wheel (please look at the review comments), otherwise it's working for me.

**Comment by redaxmedia** [comment]
@jqassar Awesome, so I merged it with the suggested changes to the master. Please do a final check until tomorrow - so I can release it asap.

Did you think about my comment at #29 ? :-)

**Comment by jqassar** [comment]
@redaxmedia , I tested the Bamboo producer with successful and failed plan and project.  Both lights (on my Mamba Wireless 2018) change appropriately, so I think this is okay for release.  Note that I don't have any devices with side or backlight lighting, so I don't know if those 'parts' are correct.

**Comment by redaxmedia** [comment]
Great, I release 7.2.0 now...
