### ISSUE TITLE
Add producer: Terraform Cloud/Enterprise

### ISSUE THREAD

**Issue by jqassar** [redaxmedia/chroma-feedback#57]
Basic information:
- Terraform Cloud accounts are free; you can make test scaffolding quite easily.
- The API for Cloud and Enterprise is equivalent.
- In TFC, an account has one or more _organizations_ .  Each organization has one or more _workspaces_.  Each workspace can have one or more _runs_.
- There isn't a 'slug' per se, but we can emulate one with the 'typical' format (org/workspace).
- All API calls require a bearer token which you can generate from your account settings.  The details of the headers to set are in the implementation.  The token should be, at a minimum, available as an environment variable (TFE_TOKEN).

Build statuses:
There are many statuses in Terraform.  Arranged in 'order' they look _mostly_ like this:
```
		# Statuses with a '*' require manual intervention in TFE.
		'pending': 'process',				# Not running yet
		'plan-queued': 'process',			# Waiting to plan
		'planning': 'process',				# Checking infrastructure
		'canceled': 'failed',				# Run was cancelled
		'discarded': 'errored',				# Plan finished but was not applied
		'planned': 'process',				# Plan succeeded, needs approval *
		'planned-and-finished': 'passed',	# No changes, infrastructure OK
		'none': 'passed',					# Never run
		'cost-estimating': 'process',		# If you have it, TF estimates cost
		'cost-estimated': 'process', 		# of infrastructure.  Automatic...
		'policy-checking': 'process',		# Sentinel policies are run
		'policy-soft-failed': 'process', 	# A soft failure can be approved *
		'policy-override': 'process', 		# Applying over soft-fail policy
		'policy-checked': 'process', 		# Automatic, proceed to pre-apply
		'confirmed': 'process',				# Plan was confirmed, apply is next
		'apply-queued': 'process',			# Waiting to apply
		'applying': 'process',				# Apply in process
		'errored': 'failed',				# Apply had an error
		'applied': 'passed'					# Apply successful
```
Note the asterisked statuses.  They are points which require manual intervention before proceeding (if the workspace is configured that way).  Because of this, I feel it necessary to add another color/effect combination to reflect the 'Needs Confirmation' status this returns in the UI.  This effect will be applied to the blink1/Razer Chroma consumers initially and is currently working.

API calls (taken from my implementation, so I'll remove the big docblock):
```
        # 
	# You can either query a workspace by id (ws-<hexstring>) or by org/ws name.
	# You can query an entire organization with just the orgname, as well.
        # 
	# 1) Single status: organizations/<organization>/workspaces/<workspace name>
	# 	- data.id - This is the workspace id (in ws-blahblah format)
	#       If you use ?include=current.run, you also get another tree:
	#       - included[0].attributes.status: <the status>
	#       Note that data holds a dict and included a list of dicts.
	#   2) Single status: workspaces/<ws-idstring>
        #     This returns the same data as 1 and is parsed equivalently.
        #     Since the caller passes in the ID, rather than return a name we call the slug 'org/ws-id...'
	#   3) Multiple status: organizations/<organization>/workspaces
	#	Here, getting every workspace status is a pain, because it
	#	paginates and the include only gives run IDs without the
	#	attached workspace.  They *do* correlate, however, with a
	#      list of attribute dicts and a list of included dicts, so we
	#	should be able to map 1:1 between:
	#	- data[n].attributes.name
	#      - included[n].attributes.status
	#	up to the pagination limit.
	#
	#	There is also a meta-information in the response which gives aggregate statuses.
	#	- meta.status-counts
        #      
        #     If we use this, we can see totals and parse, but chroma-feedback's output would only
        #     be a single line ('blah has status blah').

```

Tasks:

- [x] Add producer code
- [x] Add producer tests
- [x] Add alternate color combination for 'warning' status
- [x] Add ability to pass effect states to consumers (and optionally parse them)
- [x] Parse warning status in consumers

**Comment by jqassar** [comment]
- For the consumers for which I do not have devices, I have stubbed in the ability to parse an effect.
- The 'warning status' (amber/orange) is not a completely separate status; for producers which support outputting a specific effect (currently Terraform only, though Bamboo could also set this up with its manual stages), an effect added to a status can trigger a change in the effect produced.  The four 'main' statuses (failed, errored, process, passes) seem to be sufficient for now, but if there is an interest in a 'pending'/'warning' status, this could be made.
- The 'warning' status is tied to a pulse_device method in the consumers which support it.

**Comment by redaxmedia** [comment]
@jqassar Do you have updates on this?

**Comment by jqassar** [comment]
I do, but I can't test for a few days yet.

**Comment by redaxmedia** [comment]
Okay, in terms of testing: take a look how I mocked the Bamboo producer.

**Comment by redaxmedia** [comment]
Please reopen via PR... closing this for now
