### ISSUE TITLE
Bamboo producer needs revision

### ISSUE THREAD

**Issue by redaxmedia** [redaxmedia/chroma-feedback#65]
1. Test latest Bamboo via Docker
1. Replace local unit testing with patched unit testing to fulfill API contract

**Comment by redaxmedia** [comment]
Done

**Comment by jqassar** [comment]
Hi,

API tokens weren't added to Bamboo until version 6.10 (the most recent non-bleeding-edge release).  Many organizations using Bamboo are not going to be at that patch level yet.  Would it be possible to have the option to use either the token *or* the username/password combination until the 7.x release becomes something more usable?

**Comment by redaxmedia** [comment]
Thank you for pointing this out, I wasn't aware that something like a access token is cutting edge technology. 😬

Are you okay using an old version of Chroma Feedback until your admin has time for an Bamboo upgrade?

**Comment by jqassar** [comment]
Sadly, for Bamboo it is.  Their technology stack and feature parity has been a couple of years behind most of Atlassian's other offerings until very recently (LDAP integration, this, other functionality).

For myself, I would fork and retain both authentication methods if possible.  I support using tokens where possible, but I'm not familiar with why the old method was removed when it is a valid (if dumb) access method--I assume it was to service another card?

**Comment by redaxmedia** [comment]
There was nothing wrong with your implementation but I made the decision to switch all producers from username:password credentials to token as of security reasons.

This only works for producers that have static tokens. Jenkins and CodeShip for example work with access token that require a initial handshake using the username:password approach.

However, it is not a good idea to expose your real username:password combination using Chroma Feedback via the command line. Once they have been leaked you have serious problem and we are talking about companies infrastructure that could be damaged. Tokens on the other hand can have limited read only access and disabled super fast. Hope you get the point.

Still, I am open for a PR to restore the old feature for Bamboo but will drop in in next major release again. Is this enough time to get your admin ready for the upgrade? Haha
