### ISSUE TITLE
Filter CircleCI pipelines to monitor my own pipelines

### ISSUE THREAD

**Issue by cpoissonnier** [redaxmedia/chroma-feedback#85]
To fully fit my needs, I'd like to be able to only have the status of my own pipelines (we are a lot to trigger builds in my organization, and I don't really care if my colleague's build fails).

Luckily it seems very easy to implement so I can develop it if you want!

Would it be okay for you if I added a `circle-only-mine=true|false` parameter?

**Comment by redaxmedia** [comment]
Can you give me the output so I get an idea? I guess you are monitoring a whole organisation?

What about that?

```
--circle-slug <username/repository-a> --circle-slug <username/repository-b> ...
```

**Comment by redaxmedia** [comment]
Tipp: If you want to develop on Chroma-Feedback then copy the `chroma-feedback` file from `/bin` to the root of the repository and then run `./chroma-feedback ...`

**Comment by cpoissonnier** [comment]
We are working on a mono-repo project with 4 feature teams so there is a lot of builds and I'd like to monitor only my own builds.

I usually monitor my builds with this URL: https://app.circleci.com/pipelines/github/[ORGANISATION]/[PROJECT]?filter=mine

I tested `--producer=circle --circle-slug=github/[ORGANISATION]/[PROJECT] --circle-token=[TOKEN]` and it works fine, but it also monitors the pipelines triggered by my coworkers (aka `host + '/api/v2/project/' + slug + '/pipeline'`)

I'd like to be able to use `host + '/api/v2/project/' + slug + '/pipeline/mine'` instead (see https://circleci.com/docs/api/v2/#operation/listMyPipelines)

I'm afraid that using `--circle-slug <username>` will fetch the pipelines I have on my personal account and not my organization.

I totally get that you want to keep the API as uniform as possible, that's why I asked you first 🙂

**Comment by redaxmedia** [comment]
The weak point of most CI APIs are the lack of branch, user and pipeline scopes. The master branch should always be the standard but that is far from reality I guess.

So let me understand your problem. As I think the master and develop branches should be monitored by all team members and fixed asap even if someone else broke it. Your usecase are properly the monitor the pipeline of your own pull requests?

I found that pretty important but let's keep in mind that a mix of master, develop and my feature branches should be the way to monitor.

That being said, I am fine with `--circle-only-mine` to make your life easier.

Just send the PR and I gonna review it.

**Comment by cpoissonnier** [comment]
> So let me understand your problem. As I think the master and develop branches should be monitored by all team members and fixed asap even if someone else broke it. Your usecase is properly to monitor only the pipelines of your own pull requests?

That's exactly that, yes! We have a strong quality process on master and develop that prevent such issues, so monitoring these branches is not really what will make my life easier :)

I'll try to step up in Python and code it, don't hesitate to be challenging, I'll probably make some silly mistakes :D

**Comment by redaxmedia** [comment]
I think that would be useful for everyone... send me a PR and I gonna review it.

And don't worry, I am a beginner in Python aswell... webdev speaking :-)

**Comment by cpoissonnier** [comment]
Pull request #87 created 🙂

**Comment by redaxmedia** [comment]
Great first pull request! I reviewed it... basicly only ordering and wording stuff is left.

**Comment by redaxmedia** [comment]
@cpoissonnier Merge to master - I changed the API a bit a used a more common wording that could be applied to other producers later... `--cirlce-filter=mine`.

Give it a try local and tell me if this worked for you - I gonna release it afterwards.

**Comment by cpoissonnier** [comment]
You were too quick to let me take into account your requests :D

I just tested and it seems to work great!

Thank you Henry!

**Comment by redaxmedia** [comment]
You are welcome, I release 8.3.0 ... have fun with it
