### ISSUE TITLE
Support for Luxafor

### ISSUE THREAD

**Issue by cpoissonnier** [redaxmedia/chroma-feedback#90]
I happen to have a [Luxafor flag](https://luxafor.com/flag-usb-busylight-availability-indicator/), and I think it would be a nice thing to have into Chroma Feedback!

It has a REST API that is really easy to use: https://luxafor.helpscoutdocs.com/article/25-webhook-api-basics-and-guidelines

I think I'll be able to develop this new integration with some time.

Let me know if you are interested!

**Comment by redaxmedia** [comment]
That device is awesome or let's say a perfect match to Chroma Feedback.

We could integrate it with: https://github.com/vmitchell85/luxafor-python

**Comment by cpoissonnier** [comment]
Unfortunately, USB based scripts doesn't work on macOS, I tried multiple python scripts, and they all failed  :/

**Comment by redaxmedia** [comment]
I see... so how is their API working? You fire against an public endpoint and this redirects to a local device?

**Comment by redaxmedia** [comment]
That one claims to work under macOS: https://github.com/francjerez/flag

The hid library should work under Linux aswell...

**Comment by cpoissonnier** [comment]
Flag does not seem to work. I installed it, and I have an error 
```
Installing...
-> /Users/root/Library/LaunchAgents/com.luxafor.flag.plist
-> /Users/root/Library/Scripts/flag.py
-> /Users/root/.logouthook
Bootstrap failed: 125: Unknown error: 125
All done!
```

And it does not seem to have an API to be used by another application, and it is only made to sync "Do not distub" mode with the Flag. I'm not convinced this is a good solution.

I got confirmation that PyUSB+Luxafor does not work on macOS, HIDAPI must be used instead, but I don't see it used in any of the Python lib I saw. 

- https://github.com/fmartingr/pyluxafor : PyUSB so I got `usb.core.USBError: [Errno 13] Access denied (insufficient permissions)` both as a library and a CLI
- https://github.com/rafapi/pomolux: did not manage to run it with Python3
- https://gist.github.com/dave-irvine/dbec2584e7508cbfc79e: uses PyUSB
- https://github.com/takeontom/pyluxafor: uses PyUSB
- https://github.com/vmitchell85/luxafor-python: macOS not supported

I really think the API is the better option here. It is supported by the builder itself, it is multiplatform and easy to develop. 
I tested it, and it takes less than a second to change its color.

WDYT?

**Comment by redaxmedia** [comment]
Let me talk about their API first. This is wild guessing but I think it works similar to https://discovery.meethue.com by Philips Hue that does a socket discovery on your IP and therfore network. I did not use this for the implementation because:

1. Does not work when offline
2. Does not work behind strict network firewalls and VPNs
3. Does return just one device

That being said we properly have to live with similar limitations using the Luxafor API webhook. I wonder what happens when multiple developers with the same IP are using Chroma Feedback then - how should this work?

**Comment by redaxmedia** [comment]
The best way would be to get our heads into the HIDAPI and figure out why it is not working. The flag guy is using it here but on a specific VID and PID that is properly different on your device type:

```
vid = 0x04d8#  1240
pid = 0xf372# 62322
dev = hid.device()
```

I am not an expert but form my knowledge this is a very low level to communicate with devices. This install script is really garbage, the lib should handle that if there is something missing in the system.

**Comment by cpoissonnier** [comment]
> Does not work when offline
Does using Chroma Feedback offline is relevant? All providers are SaaS, right?

> Does return just one device
&
> I wonder what happens when multiple developers with the same IP are using Chroma Feedback then - how should this work?

In `userId` in the body of the request sent to Luxafor API seems to actually be a kind of "deviceId". I think this is not an issue. Unfortunately, I can't test it as I only have one Luxafor device 😕

**Comment by redaxmedia** [comment]
Well, I don't have a problem that we integrate the webhook API first and later try to switch it... is this a deal?

**Comment by cpoissonnier** [comment]
Deal !

**Comment by redaxmedia** [comment]
Waiting for the PR then... great

**Comment by cpoissonnier** [comment]
There it is ! #91

**Comment by redaxmedia** [comment]
I merged it and will give it a little code revision...
